name: moajmalnk
description: "Ajmal Nk, a leading Freelance Web Developer in Kerala, offers top-tier web development solutions. Choose the best for tailored freelance services!"
publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  webview_flutter: ^4.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.0.15
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.0.0

flutter:
  uses-material-design: true